Repository AY2425S2-CS2103-F10-4/tp, pull requests merged in 2025-03, with the labels that each got.

#38 Update Add command by adding Tuition Time feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TuitionTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#48 Fix TuitionTime Format Handling and Update Output JAR Name
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#56 Update help feature
  build.gradle
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/CommandConfig.java
  src/main/java/seedu/address/ui/CommandUsageInfo.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/WrappedTextTableCellFactory.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/ui/CommandConfigTest.java
  src/test/java/seedu/address/ui/CommandUsageInfoTest.java
Labels: type.Enhancement

#58 Update UML Diagrams to Reflect SortCommand, CommandHistoryManager, and HelpWindow Enhancements
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Low

#61 Update uml diagram and project website
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/helpMessage.png
  docs/index.md
Labels: type.Task
