Repository AY2425S2-CS2103-F10-4/tp, pull requests merged in 2025-04, with the labels that each got.

#67 Enable assertion
  build.gradle
Labels: type.Task

#73 Update clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: alpha-bug

#74 Fix bug add
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TuitionTime.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: alpha-bug

#80 Fix invalid tuition time parsed successfully
  src/main/java/seedu/address/model/person/TuitionTime.java
  src/test/java/seedu/address/model/person/TuitionTimeTest.java
Labels: alpha-bug

#81 Make help message clearer
  src/main/java/seedu/address/ui/CommandConfig.java
Labels: alpha-bug

#84 Make command parsing case-insensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: alpha-bug

#86 Correct sort by name desc logic for name field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/ui/CommandConfig.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: alpha-bug

#95 Fix alpha bugs
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CommandHistoryManager.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/TagsContainKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#153 Fix bugs v1.6
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug

#154 Improve UI
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, type.Bug

#159 Update Implementation section of DG
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
Labels: type.Bug

#161 Fix the RTL bug by clarifying the context and update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug
